baseurl = "https://chuangyu-tian.github.io/home/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "Chuangyu-Tian | 田创宇"
theme = "hugo-ivy"
#googleAnalytics = "UA-112592341-1"
disqusShortname = "home-xjdzylqrzp"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
MetaDataFormat = "yaml" # format of a new post
enableGitInfo = false
publishDir = "docs"

[[menu.main]]
    name = "English"
    url = "/en／"
    weight = 1

[[menu.main]]
    name = "中文"
    url = "/cn/"
    weight = 2

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2

[[menu.en]]
    name = "Blog"
    url = "/en/post/"
    weight = 3

[[menu.en]]
    name = "Software"
    url = "/en/tools/"
    weight = 4

[[menu.en]]
    name = "List"
    url = "/en/list/"
    weight = 5

[[menu.en]]
    name = "CV"
    url = "/en/cv-en/Chuangyu-Tian"
    weight = 6


[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 7

[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2

[[menu.cn]]
    name = "博客"
    url = "/cn/post/"
    weight = 3

[[menu.cn]]
    name = "读书"
    url = "/cn/read/"
    weight = 4

[[menu.cn]]
    name = "写作"
    url = "/cn/writing"
    weight = 5

[[menu.cn]]
    name = "研究"
    url = "/cn/research/"
    weight = 6

[[menu.cn]]
    name = "工具"
    url = "/cn/tools/"
    weight = 7

[[menu.cn]]
    name = "简历"
    url = "/cn/cv-cn/Chuangyu-Tian"
    weight = 8

[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 9

[params]
    description = "Personal website of Chuangyu-Tian; 田创宇的个人网站"
    disqusURL = "https://chuangyu-tian.github.io/home/"
    customJS = ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js", "js/header-link.js"]
    githubContentURL = "？？？"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsTheme = "github"
    dateFormat = "2006-01-02" # "2006-01-02, Mon, "

[params.footer]
    home = "Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/) &copy; [Chuangyu-Tian](/) 2020 - 20??"
    en   = "[<i class='far fa-envelope fa-1x'></i>](mailto:tcy06142476@163.com) &middot; [<i class='fab fa-github fa-1x'></i>](https://github.com/Chuangyu-Tian) &middot; <br> Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/) &copy; [Chuangyu-Tian](/) 2020 - "
    cn   = "[<i class='far fa-envelope fa-1x'></i>](mailto:tcy06142476@163.com) &middot; [<i class='fab fa-github fa-1x'></i>](https://github.com/Chuangyu-Tian) &middot; <br> 本站由 [Hugo](https://gohugo.io) 和 [Blogdown](https://bookdown.org/yihui/blogdown/) 强力驱动 &copy; [田创宇](/) 2020-"

[params.author]
    en = "Chuangyu-Tian"
    cn = "田创宇"

[params.logo.en]
    img = "https://avatars1.githubusercontent.com/u/25057508?s=460&v=4"
    url = "/"
    alt = "Shixiang Wang"
    tag = ""

[params.lang.edit]
    cn = "编辑"
[params.lang.license]
    cn = "版权"
[params.lang.subscribe]
    cn = "订阅"
